package com.louis.ling.admin.model;

import java.util.Date;

public class sysUserToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.id
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.user_id
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.expire_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.create_by
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.create_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.last_update_by
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private String lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_token.last_update_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.id
     *
     * @return the value of sys_user_token.id
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.id
     *
     * @param id the value for sys_user_token.id
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.user_id
     *
     * @return the value of sys_user_token.user_id
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.user_id
     *
     * @param userId the value for sys_user_token.user_id
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.token
     *
     * @return the value of sys_user_token.token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.token
     *
     * @param token the value for sys_user_token.token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.expire_time
     *
     * @return the value of sys_user_token.expire_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.expire_time
     *
     * @param expireTime the value for sys_user_token.expire_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.create_by
     *
     * @return the value of sys_user_token.create_by
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.create_by
     *
     * @param createBy the value for sys_user_token.create_by
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.create_time
     *
     * @return the value of sys_user_token.create_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.create_time
     *
     * @param createTime the value for sys_user_token.create_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.last_update_by
     *
     * @return the value of sys_user_token.last_update_by
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.last_update_by
     *
     * @param lastUpdateBy the value for sys_user_token.last_update_by
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_token.last_update_time
     *
     * @return the value of sys_user_token.last_update_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_token.last_update_time
     *
     * @param lastUpdateTime the value for sys_user_token.last_update_time
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}