package com.louis.ling.admin.dao;

import com.louis.ling.admin.model.sysDict;
import com.louis.ling.admin.model.sysDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int countByExample(sysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int deleteByExample(sysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int insert(sysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int insertSelective(sysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    List<sysDict> selectByExample(sysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    sysDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") sysDict record, @Param("example") sysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByExample(@Param("record") sysDict record, @Param("example") sysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByPrimaryKeySelective(sysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByPrimaryKey(sysDict record);

    List<sysDict> findPage();

    List<sysDict> findPageByLabel(@Param(value="label") String label);

    List<sysDict> findByLable(@Param(value="label") String label);
}