package com.louis.ling.admin.dao;

import com.louis.ling.admin.model.sysUserToken;
import com.louis.ling.admin.model.sysUserTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysUserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int countByExample(sysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int deleteByExample(sysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int insert(sysUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int insertSelective(sysUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    List<sysUserToken> selectByExample(sysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    sysUserToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") sysUserToken record, @Param("example") sysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByExample(@Param("record") sysUserToken record, @Param("example") sysUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByPrimaryKeySelective(sysUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_token
     *
     * @mbggenerated Fri Jun 19 15:59:56 CST 2020
     */
    int updateByPrimaryKey(sysUserToken record);
}